### ISSUE TITLE
Building for Windows. Adding path to windows libraries?

### ISSUE THREAD

**Issue by Marcets423** [styluslabs/ugui-example#1]
Hello, Thank you for this example repo. I'm trying to build it on Windows 10 but have been running into some issues in the make process. I'm not so knowledgeable with makefiles so maybe It's just a simple adjustment I need to make.

The lib files in the makefile cannot be linked. This is because it is looking for them in the directory of the makefile. Technically, one could move all the lib files needed but that would be too many to move into the repo (because the libs included in the makefile includes additional libraries as well). I'm thinking that I should be able to set additional library paths where _make_ looks for the libraries needed.

I've tried with both the /MD flag and the /MT flag.

Any ideas on how I can properly link the windows libraries when running make?

Thank you for any help!

Martin

**Comment by styluslabs** [comment]
Are you running from a Visual Studio command prompt, e.g., "x64 Native
Tools Command Prompt"?  If so, can you paste the error message here?

**Comment by Marcets423** [comment]
Thanks for pointing that out. I was using the command prompt which was causing the missing libraries errors. I tried this due to the Native Tools command prompt not working either with the error message:
 "_LIBCMT.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)_".  I now see that this is the issue to solve.
 
One thing I've noted is that when I clone the repo (with recurse submodules) the submodules are checked out on specific commits, and I have to update at least the ugui submodule because the commit checked out when cloning does not have the file "_makefile.msvc_" . 
 
The error above is from only having updated the ugui submodule to master.
 
 I have tried updating all submodules to their master branch, which caused errors with the layout library due to the file "_layout.c_" having been removed at some point between the referenced commit and master.
 
 I have also tried updating only the submodules owned by styluslabs. Usvg added other errors in that case:
 
_**svgparser.obj : error LNK2019:** unresolved external symbol "class std::vector<unsigned char,class std::allocator<unsigned char> > __cdecl base64_decode(char const *,unsigned __int64)" (?base64_decode@@YA?AV?$vector@EV?$allocator@E@std@@@std@@PEBD_K@Z) referenced in function "private: class SvgNode * __cdecl SvgParser::createImageNode(void)" (?createImageNode@SvgParser@@AEAAPEAVSvgNode@@XZ)

**svgwriter.obj : error LNK2019**: unresolved external symbol "char * __cdecl base64_encode(unsigned char const *,unsigned __int64,char *)" (?base64_encode@@YAPEADPEBE_KPEAD@Z) referenced in function "private: void __cdecl SvgWriter::_serialize(class SvgImage *)" (?_serialize@SvgWriter@@AEAAXPEAVSvgImage@@@Z)

**LIBCMT.lib(exe_winmain.obj) : error LNK2019**: unresolved external symbol WinMain referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)_
 
 Run with "x64 Native Tools Command Prompt for VS 2019"
 I hope this makes sense. Thanks for your help!

**Comment by styluslabs** [comment]
WinMain would be provided by SDL and the other errors you found look like
ulib might have been missed.

I have updated ugui-example, ulib, usvg, and ugui and tested on Windows
with the exact commits now referenced in ugui-example using "x64 Native
Tools Command Prompt for VS 2017" and GNU make (see README in nanovgXC),
with the SDL folder inside ugui-example (containing statically linked
SDL/Release/SDL2.lib and SDL/include/).  If you are using the prebuilt SDL
libraries for dynamic linking, you'll have to edit Makefile to include both
SDL2.lib and SDL2main.lib in WIN_LIBS.  If you want to try the exact build
I'm doing, you can check out https://github.com/pbsurf/SDL/tree/write-win
and build the static library w/ "make -f SDL-Makefile.msvc"

**Comment by Marcets423** [comment]
This worked like a charm. For the GLFW example, I had to add the linker flag  "_/NODEFAULTLIB:LIBCMT_". 

Thank you for your help.
Martin
